### ISSUE TITLE
_attention_rel_h_rel_w_kernel_aligned_device not receiving correct dtype

### ISSUE THREAD

**Issue by geodavic** [pytorch-labs/segment-anything-fast#66]
I am trying to use `set_image` from `SamPredictor`:
```
import numpy as np
from PIL import Image
from segment_anything_fast import SamPredictor, sam_model_registry
sam = sam_model_registry["vit_h"](checkpoint="<path/to/checkpoint>").cuda()

predictor = SamPredictor(sam)
img = np.array(Image.open("path/to/img"))
predictor.set_image(img)
```
which returns the error:
```
Loading best configs from file /home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/configs/flash_4_configs_a100.p
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/predictor.py", line 90, in set_torch_image
    self.features = self.model.image_encoder(input_image.to(model_dtype))
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/modeling/image_encoder.py", line 113, in forward
    x = blk(x)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/modeling/image_encoder.py", line 175, in forward
    x = self.attn(x)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/modeling/image_encoder.py", line 245, in forward
    x = _attention_rel_h_rel_w(q, k, v, rel_h, rel_w)
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/flash_4.py", line 337, in _attention_rel_h_rel_w
    o = torch.ops.customflash.custom_flash_aligned(
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/torch/_ops.py", line 760, in __call__
    return self._op(*args, **kwargs or {})
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/flash_4.py", line 298, in _attention_rel_h_rel_w_kernel_aligned
    _attention_rel_h_rel_w_kernel_aligned_device(q,
  File "/home/gtorres/anaconda3/envs/sam-fast/lib/python3.9/site-packages/segment_anything_fast/flash_4.py", line 185, in _attention_rel_h_rel_w_kernel_aligned_device
    assert (q.dtype == torch.bfloat16 or q.dtype == torch.float16)
AssertionError
```

I have installed following the instructions in the README in a fresh environment.

**Comment by Chris-toe-pher** [comment]
--- a/segment_anything_fast/flash_4.py
+++ b/segment_anything_fast/flash_4.py
@@ -264,8 +264,12 @@ def _attention_rel_h_rel_w_kernel_aligned(q, k, v, rel_h_w, sm_scale):
     # is guaranteed to fail. If the inputs are already contiguous
     # these are cheap checks via is_contiguous and do nothing.
     q = q.contiguous()
+    q = q.to(torch.float16)
     k = k.contiguous()
+    k = k.to(torch.float16)
     v = v.contiguous()
+    v = v.to(torch.float16)
+    rel_h_w = rel_h_w.to(torch.float16)
     # shape constraints
     Lq, Lk, Lv = q.shape[-1], k.shape[-1], v.shape[-1]
     assert Lq == Lk and Lk == Lv

**Comment by cpuhrsch** [comment]
I'll push a dtype guard as well. Please note that using float16 or bfloat16 works best.

I created a small tool to help you change the dtype.

Example usage:

```
import torch
from segment_anything_fast import sam_model_registry, SamPredictor
checkpoint_path = 'sam_vit_h_4b8939.pth'
sam = sam_model_registry['vit_h'](checkpoint=checkpoint_path).cuda()
predictor = SamPredictor(sam)

from segment_anything_fast import tools
predictor = tools.apply_eval_dtype_predictor(predictor, torch.bfloat16)
```

Definition is here: https://github.com/pytorch-labs/segment-anything-fast/blob/7cd6ba3cea451602acb7d36d176da06c70ac68f1/segment_anything_fast/tools.py#L22-L36

**Comment by cpuhrsch** [comment]
Ok, I also tried to address this in https://github.com/pytorch-labs/segment-anything-fast/pull/67 . Please try again and let me know if it doesn't work :)

**Comment by geodavic** [comment]
@cpuhrsch thank you -- I just tried `predictor = tools.apply_eval_dtype_predictor(predictor, torch.bfloat16)` and I got a different error:

```
  File "/home/gtorres/models/sam/fast-annotation-model/model.py", line 64, in forward
    self.predictor.set_image(x)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/segment_anything_fast/predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/segment_anything_fast/predictor.py", line 90, in set_torch_image
    self.features = self.model.image_encoder(input_image.to(model_dtype))
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/segment_anything_fast/modeling/image_encoder.py", line 113, in forward
    x = blk(x)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/segment_anything_fast/modeling/image_encoder.py", line 175, in forward
    x = self.attn(x)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/torch/nn/modules/module.py", line 1510, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/torch/nn/modules/module.py", line 1519, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/segment_anything_fast/modeling/image_encoder.py", line 245, in forward
    x = _attention_rel_h_rel_w(q, k, v, rel_h, rel_w)
  File "/home/gtorres/models/sam/fast-annotation-model/pkg/segment_anything_fast/flash_4.py", line 369, in _attention_rel_h_rel_w
    return torch.nn.functional.scaled_dot_product_attention(q_, k_, v_, attn_mask=attn_bias)
RuntimeError: cutlassF: no kernel found to launch!
```

**Comment by geodavic** [comment]
Others have resolved this error with:
```
torch.backends.cuda.enable_mem_efficient_sdp(False)
torch.backends.cuda.enable_flash_sdp(False)
```

So I added that, and it appears to have helped but then I get:

```
Warning: Custom flash attention kernels were written specifically for A100.
We will try to read previously created kernel configurations from /home/gtorres/models/sam/fast-annotation-model/flash_4_configs.p.
You can disable this kernel by setting SEGMENT_ANYTHING_FAST_USE_FLASH_4=0
key  (torch.Size([1, 16, 4096, 128]), torch.Size([1, 16, 4096, 128]), torch.Size([1, 16, 4096, 128]), torch.Size([1, 16, 4096, 128]), torch.Size([1, 16, 4096, 128]), (8388608, 524288, 128, 1), (8388608, 524288, 128, 1), (8388608, 524288, 128, 1), (8388608, 524288, 128, 1), (8388608, 524288, 128, 1))  not found. Running autotune. This might take a while.
all configs len:  60
Unsupported conversion from bf16 to f16

UNREACHABLE executed at /tmp/tmp5k2sgro3/triton/lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp:584!
Aborted (core dumped)
```

**Comment by geodavic** [comment]
I switched to `torch.float16` and got virtually the same error, but with this one line different:

```
Unsupported conversion from f16 to f16
```

🤔

**Comment by cpuhrsch** [comment]
Hm, @geodavic can you try running with `SEGMENT_ANYTHING_FAST_USE_FLASH_4=0`? Also, are you using the latest PyTorch nightly?

Thank you!

**Comment by geodavic** [comment]
@cpuhrsch That worked, thank you! (I thought I had tried that and it failed, but I now it is working).

Do you know if disabling FLASH_4 in that way will hurt inference speed? I am seeing a roughly 10% speedup over regular SAM for computing the image embedding (not as much as I was hoping for).

**Comment by cpuhrsch** [comment]
@geodavic - Yes, flash_4 helps a lot. What kind of GPU are you running on and what batch size? We optimized mostly for A100.

**Comment by cpuhrsch** [comment]
@geodavic I'm going to close this now since the issue seems to be resolved, but please reopen if that's not the case.
